#!/bin/bash

# Explode the image into its bytes and write them to the framebuffer
if [ -z "$1" ]
  then
    python image_to_binary.py -i test.png -o /dev/fb0 -w 768 -h 1024
  else
    python image_to_binary.py -i $1 -o /dev/fb0 -w 768 -h 1024
fi

# Force a screen refresh
echo 1 > /sys/devices/platform/mxc_epdc_fb/mxc_epdc_update
