#!/bin/bash
chroot /mnt/debian /debootstrap/debootstrap --second-stage

# Copy the kindle's DNS servers to the debian image
cp /etc/resolv.conf /mnt/debian/etc/resolv.conf

echo "deb http://ftp.au.debian.org/debian stable main contrib non-free
deb-src http://ftp.au.debian.org/debian stable main contrib non-free

deb http://ftp.debian.org/debian/ wheezy-updates main contrib non-free
deb-src http://ftp.debian.org/debian/ wheezy-updates main contrib non-free

deb http://security.debian.org/ wheezy/updates main contrib non-free
deb-src http://security.debian.org/ wheezy/updates main contrib non-free
" >> /mnt/debian/etc/apt/sources.list


chroot /mnt/debian apt-get update
chroot /mnt/debian apt-get install python python-imaging git -y
chroot /mnt/debian apt-get clean
chroot /mtn/debian https://github.com/TobiasWooldridge/KindleScripts.git /root/scripts
